import * as stylex from '@stylexjs/stylex';

/* ────────────────────────────────────────────────────────────────────────────
 * Design tokens
 *
 * Colors resolve against the runtime `--pf-*` variables written synchronously
 * by the theme preset script (layouts + home page). Fallbacks keep pages
 * readable if the script is absent. Fixed semantic colors (destructive,
 * success, warning) are literal; everything else adapts to light/dark/presets.
 * ──────────────────────────────────────────────────────────────────────────── */

const FONT_SANS = "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif";
const FONT_HEADING = "'Teko', 'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif";
const FONT_JAKARTA = "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif";
const FONT_MONO = "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

const spin = stylex.keyframes({
    to: { transform: 'rotate(360deg)' },
});

export const styles = stylex.create({
    /* ── Shells (body) ─────────────────────────────────────────── */
    authBody: {
        minHeight: '100vh',
        overflowX: 'hidden',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
        backgroundColor: 'var(--pf-bg, #030712)',
        color: 'var(--pf-text, #ffffff)',
    },
    appBody: {
        minHeight: '100vh',
        backgroundColor: 'var(--pf-bg, #030712)',
        color: 'var(--pf-text, #ffffff)',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
    },
    appMain: {
        marginInline: 'auto',
        maxWidth: '80rem',
        paddingInline: '1rem',
        paddingBlock: '2rem',
        '@media (min-width: 40rem)': { paddingInline: '1.5rem' },
        '@media (min-width: 64rem)': { paddingInline: '2rem' },
    },

    /* ── App layout shell ──────────────────────────────────────── */
    appShell: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
    },
    appLayout: {
        position: 'relative',
        flex: 1,
        display: 'flex',
        minHeight: 0,
    },
    appSidebar: {
        display: 'none',
        '@media (min-width: 64rem)': {
            display: 'block',
            position: 'sticky',
            top: '4rem',
            height: 'calc(100vh - 4rem)',
            width: '15rem',
            flexShrink: 0,
            overflowY: 'auto',
            borderRightWidth: 1,
            borderRightStyle: 'solid',
            borderRightColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
            paddingBlock: '1.5rem',
            paddingInline: '1rem',
        },
    },
    appNav: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.25rem',
    },
    appNavLabel: {
        fontFamily: FONT_MONO,
        marginBottom: '0.25rem',
        paddingInline: '0.75rem',
        fontSize: '10px',
        fontWeight: 600,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 60%, transparent)',
    },
    appNavGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.125rem',
    },
    appNavGroupToggle: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        width: '100%',
        paddingInline: '0.75rem',
        paddingBlock: '0.5rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
        borderRadius: '0.5rem',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        cursor: 'pointer',
        borderWidth: 0,
        backgroundColor: 'transparent',
        textAlign: 'left',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
        },
    },
    appNavGroupIcon: {
        flexShrink: 0,
        height: '1rem',
        width: '1rem',
    },
    appNavGroupIconWrap: {
        display: 'inline-flex',
        transitionProperty: 'transform',
        transitionDuration: '200ms',
    },
    appNavGroupIconOpen: {
        transform: 'rotate(90deg)',
    },
    appNavGroupBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.125rem',
        paddingLeft: '1.75rem',
    },
    appNavLink: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.625rem',
        borderRadius: '0.5rem',
        paddingInline: '0.75rem',
        paddingBlock: '0.5rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    appNavLinkActive: {
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 12%, transparent)',
        color: 'var(--pf-c1, #6429ed)',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 18%, transparent)',
            color: 'var(--pf-c1, #6429ed)',
        },
    },
    appNavIcon: { flexShrink: 0, height: '1rem', width: '1rem' },
    appMainFlex: { flex: 1, minWidth: 0 },

    /* ── Auth header (x-auth.header) ───────────────────────────── */
    authHeader: {
        position: 'sticky',
        top: 0,
        zIndex: 50,
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-bg, #030712) 80%, transparent)',
        backdropFilter: 'blur(20px)',
    },
    authHeaderInner: {
        maxWidth: '80rem',
        marginInline: 'auto',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingInline: '1rem',
        paddingBlock: '0.75rem',
        '@media (min-width: 40rem)': { paddingInline: '1.5rem' },
    },
    brand: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.625rem',
    },
    brandMark: {
        display: 'flex',
        height: '2.25rem',
        width: '2.25rem',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.5rem',
        backgroundColor: 'var(--pf-accent, #00e5fd)',
        color: '#04201f',
        fontFamily: FONT_MONO,
        fontSize: '0.75rem',
        fontWeight: 600,
        transitionProperty: 'box-shadow',
        transitionDuration: '200ms',
        ':hover': {
            boxShadow: '0 3px 0 -1px color-mix(in srgb, var(--pf-accent, #00e5fd) 45%, transparent)',
        },
    },
    brandText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'color-mix(in srgb, var(--pf-text, #fff) 90%, transparent)',
    },
    headerLink: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color',
        transitionDuration: '200ms',
        ':hover': { color: 'var(--pf-text, #fff)' },
    },
    headerLinkStrong: {
        fontWeight: 600,
    },

    /* ── Auth page shells (login / forgot / reset / confirm / verify) ── */
    authMain: {
        marginInline: 'auto',
        display: 'flex',
        minHeight: 'calc(100vh - 61px)',
        maxWidth: '32rem',
        alignItems: 'center',
        paddingInline: '1rem',
        paddingBlock: '3rem',
        '@media (min-width: 40rem)': { paddingInline: '1.5rem' },
    },
    authInner: { width: '100%' },
    titleBlock: {
        marginBottom: '2rem',
        textAlign: 'center',
    },
    authTitle: {
        fontFamily: FONT_HEADING,
        fontSize: '2.25rem',
        fontWeight: 700,
        letterSpacing: '-0.025em',
        color: 'var(--pf-text, #fff)',
        lineHeight: 1.1,
        '@media (min-width: 40rem)': { fontSize: '3rem' },
    },
    authTitleXl: {
        '@media (min-width: 40rem)': { fontSize: '3.75rem' },
    },
    authSubtitle: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.75rem',
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    authFooter: {
        fontFamily: FONT_JAKARTA,
        marginTop: '1.5rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.75rem',
        fontSize: '0.75rem',
        color: 'color-mix(in srgb, var(--pf-text, #fff) 70%, transparent)',
    },

    /* ── Register page shells ──────────────────────────────────── */
    registerMain: {
        marginInline: 'auto',
        maxWidth: '80rem',
        paddingInline: '1rem',
        paddingBlock: '2.5rem',
        '@media (min-width: 40rem)': { paddingInline: '1.5rem' },
    },
    registerTitleBlock: {
        marginInline: 'auto',
        marginBottom: '2rem',
        maxWidth: '48rem',
        textAlign: 'center',
    },
    registerForm: {
        marginInline: 'auto',
        display: 'grid',
        maxWidth: '64rem',
        gap: '2rem',
        '@media (min-width: 64rem)': { gridTemplateColumns: '1fr 320px' },
    },
    stepPanel: {
        overflow: 'hidden',
        borderRadius: '1rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
    },
    stepHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        paddingInline: '1.5rem',
        paddingBlock: '1rem',
        '@media (min-width: 40rem)': { paddingInline: '2rem' },
    },
    stepHeaderTitle: {
        fontFamily: FONT_HEADING,
        fontSize: '1.5rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    stepHeaderMeta: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    stepBody: {
        paddingInline: '1.5rem',
        paddingBlock: '2rem',
        '@media (min-width: 40rem)': { paddingInline: '2rem' },
    },
    stepInner: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },

    /* ── Error banner ──────────────────────────────────────────── */
    errorBanner: {
        marginInline: '1.5rem',
        marginTop: '1rem',
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, #f87171 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #f87171 10%, transparent)',
        paddingInline: '1rem',
        paddingBlock: '0.75rem',
        '@media (min-width: 40rem)': { marginInline: '2rem' },
    },
    errorBannerIcon: {
        flexShrink: 0,
        height: '1rem',
        width: '1rem',
        color: '#f87171',
    },
    errorBannerText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: '#f87171',
    },
    errorBannerClose: {
        marginLeft: 'auto',
        color: 'color-mix(in srgb, #f87171 60%, transparent)',
        transitionProperty: 'color',
        transitionDuration: '200ms',
        ':hover': { color: '#f87171' },
    },

    /* ── UI primitives ─────────────────────────────────────────── */
    card: {
        borderRadius: '1rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        color: 'var(--pf-text, #fff)',
    },
    cardPad: {
        padding: '1.5rem',
        '@media (min-width: 40rem)': { padding: '2rem' },
    },

    btn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        borderRadius: '0.75rem',
        fontFamily: FONT_JAKARTA,
        fontWeight: 700,
        transitionProperty: 'color, background-color, border-color, box-shadow, transform, opacity',
        transitionDuration: '200ms',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        cursor: 'pointer',
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 60%, transparent)',
        },
        ':disabled': {
            pointerEvents: 'none',
            opacity: 0.4,
        },
        ':active': { transform: 'scale(0.98)' },
    },
    btnPrimary: {
        backgroundColor: 'var(--pf-c1, #6429ed)',
        color: '#ffffff',
        boxShadow: '0 10px 20px -5px color-mix(in srgb, var(--pf-c1, #6429ed) 25%, transparent)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 85%, transparent)' },
    },
    btnOutline: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
        backgroundColor: 'transparent',
        color: 'var(--pf-text, #fff)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)' },
    },
    btnGhost: {
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    btnSecondary: {
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
        color: 'var(--pf-text, #fff)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)' },
    },
    btnDestructive: {
        backgroundColor: '#f87171',
        color: '#ffffff',
        ':hover': { backgroundColor: 'color-mix(in srgb, #f87171 90%, transparent)' },
    },
    btnAccent: {
        backgroundColor: 'var(--pf-accent, #00e5fd)',
        color: '#030712',
        boxShadow: '0 10px 20px -5px color-mix(in srgb, var(--pf-accent, #00e5fd) 25%, transparent)',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--pf-accent, #00e5fd) 90%, transparent)' },
    },
    btnSm: {
        height: '2.25rem',
        paddingInline: '1rem',
        fontSize: '0.875rem',
    },
    btnDefault: {
        height: '2.75rem',
        paddingInline: '1.5rem',
        fontSize: '0.875rem',
    },
    btnLg: {
        height: '3rem',
        paddingInline: '2rem',
        fontSize: '1rem',
    },
    btnIcon: {
        height: '2.5rem',
        width: '2.5rem',
    },
    btnGradient: {
        backgroundImage: 'linear-gradient(to right, var(--pf-c1, #6429ed), var(--pf-c2, #a855f7))',
        ':hover': {
            backgroundImage: 'linear-gradient(to right, var(--pf-c1, #6429ed), var(--pf-c2, #a855f7))',
            boxShadow: '0 10px 20px -5px color-mix(in srgb, var(--pf-c1, #6429ed) 25%, transparent)',
        },
    },

    input: {
        display: 'block',
        width: '100%',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text, #fff)',
        transitionProperty: 'border-color, box-shadow, background-color',
        transitionDuration: '200ms',
        '::placeholder': { color: 'color-mix(in srgb, var(--pf-text, #fff) 75%, transparent)' },
        ':focus': {
            borderColor: 'var(--pf-c1, #6429ed)',
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 40%, transparent)',
        },
        ':disabled': {
            cursor: 'not-allowed',
            opacity: 0.5,
        },
    },
    inputPad: {
        paddingInline: '1rem',
        paddingBlock: '0.625rem',
    },
    inputInvalid: {
        display: 'block',
        width: '100%',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, #f87171 60%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text, #fff)',
        transitionProperty: 'border-color, box-shadow, background-color',
        transitionDuration: '200ms',
        '::placeholder': { color: 'color-mix(in srgb, var(--pf-text, #fff) 75%, transparent)' },
        ':focus': {
            borderColor: '#f87171',
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, #f87171 40%, transparent)',
        },
        ':disabled': {
            cursor: 'not-allowed',
            opacity: 0.5,
        },
    },
    inputInvalidPad: {
        paddingInline: '1rem',
        paddingBlock: '0.625rem',
    },
    inputPadPr: {
        paddingInline: '1rem',
        paddingBlock: '0.625rem',
        paddingRight: '3rem',
    },
    inputPadPr12: {
        paddingInline: '1rem',
        paddingBlock: '0.625rem',
        paddingRight: '5rem',
    },

    labelRow: {
        marginBottom: '0.5rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    label: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 600,
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
    },
    hint: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 500,
        transitionProperty: 'color',
        transitionDuration: '200ms',
    },
    errorText: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.375rem',
        fontSize: '0.75rem',
        color: '#f87171',
    },

    checkbox: {
        height: '1rem',
        width: '1rem',
        flexShrink: 0,
        borderRadius: '0.25rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        accentColor: 'var(--pf-c1, #6429ed)',
        transitionProperty: 'background-color, border-color',
        transitionDuration: '200ms',
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 50%, transparent)',
        },
        ':disabled': {
            cursor: 'not-allowed',
            opacity: 0.5,
        },
    },
    checkboxWrap: {
        display: 'flex',
        cursor: 'pointer',
        alignItems: 'center',
        gap: '0.625rem',
    },
    checkboxLabel: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    termsWrap: {
        display: 'flex',
        cursor: 'pointer',
        alignItems: 'flex-start',
        gap: '0.75rem',
    },
    termsBox: {
        marginTop: '0.125rem',
        height: '1rem',
        width: '1rem',
        borderRadius: '0.25rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        accentColor: 'var(--pf-c1, #6429ed)',
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 50%, transparent)',
        },
    },
    termsText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },

    alert: {
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        paddingInline: '1rem',
        paddingBlock: '0.75rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
    },
    alertSuccess: {
        borderColor: 'color-mix(in srgb, #34d399 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #34d399 10%, transparent)',
        color: '#34d399',
    },
    alertDestructive: {
        borderColor: 'color-mix(in srgb, #f87171 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #f87171 10%, transparent)',
        color: '#f87171',
    },
    alertWarning: {
        borderColor: 'color-mix(in srgb, #fbbf24 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #fbbf24 10%, transparent)',
        color: '#fbbf24',
    },
    alertDefault: {
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },

    badge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        borderRadius: '9999px',
        borderWidth: 1,
        borderStyle: 'solid',
        paddingInline: '0.625rem',
        paddingBlock: '0.125rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '11px',
        fontWeight: 600,
    },
    badgeDefault: {
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    badgePrimary: {
        borderColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 10%, transparent)',
        color: 'var(--pf-c1, #6429ed)',
    },
    badgeSuccess: {
        borderColor: 'color-mix(in srgb, #34d399 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, #34d399 10%, transparent)',
        color: '#34d399',
    },
    badgeDestructive: {
        borderColor: 'color-mix(in srgb, #f87171 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, #f87171 10%, transparent)',
        color: '#f87171',
    },
    badgeWarning: {
        borderColor: 'color-mix(in srgb, #fbbf24 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, #fbbf24 10%, transparent)',
        color: '#fbbf24',
    },
    badgeAccent: {
        borderColor: 'color-mix(in srgb, var(--pf-accent, #00e5fd) 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-accent, #00e5fd) 10%, transparent)',
        color: 'var(--pf-accent, #00e5fd)',
    },

    separator: {
        height: '1px',
        width: '100%',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },

    /* ── Field helpers (register steps) ────────────────────────── */
    formLabel: {
        fontFamily: FONT_JAKARTA,
        marginBottom: '0.5rem',
        display: 'block',
        fontSize: '0.75rem',
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
    },
    fieldWrap: { position: 'relative' },
    iconBtn: {
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        right: '0.75rem',
        padding: '0.375rem',
        borderRadius: '0.375rem',
        borderStyle: 'none',
        color: 'var(--pf-c1, #6429ed)',
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 12%, transparent)',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 22%, transparent)',
            color: 'var(--pf-c1, #6429ed)',
        },
    },
    iconBtnGen: {
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        right: '3rem',
        padding: '0.375rem',
        borderRadius: '0.375rem',
        borderStyle: 'none',
        color: 'var(--pf-c1, #6429ed)',
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 12%, transparent)',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 22%, transparent)',
            color: 'var(--pf-c1, #6429ed)',
        },
    },
    strengthBlock: { marginTop: '1rem' },
    strengthHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    strengthLabel: {
        fontFamily: FONT_JAKARTA,
        fontSize: '10px',
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
    },
    strengthValue: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 700,
    },
    strengthTrack: {
        marginTop: '0.5rem',
        height: '0.375rem',
        overflow: 'hidden',
        borderRadius: '9999px',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
    },
    strengthFill: {
        height: '100%',
        borderRadius: '9999px',
        transitionProperty: 'width, background-color',
        transitionDuration: '300ms',
    },
    matchText: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.375rem',
        fontSize: '0.75rem',
    },
    stepFooter: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: '0.5rem',
    },
    stepFooterRev: {
        display: 'flex',
        flexDirection: 'column-reverse',
        alignItems: 'center',
        gap: '0.75rem',
        paddingTop: '0.5rem',
        '@media (min-width: 40rem)': {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
    },

    /* ── Register progress ─────────────────────────────────────── */
    progressWrap: {
        marginInline: 'auto',
        marginBottom: '2.5rem',
        display: 'flex',
        maxWidth: '42rem',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    progressStep: { display: 'flex', alignItems: 'center' },
    progressCol: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    progressCircle: {
        display: 'flex',
        height: '2.5rem',
        width: '2.5rem',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '9999px',
        borderWidth: 1,
        borderStyle: 'solid',
        fontFamily: FONT_HEADING,
        fontSize: '1.125rem',
        fontWeight: 700,
        transitionProperty: 'all',
        transitionDuration: '300ms',
    },
    progressActive: {
        borderColor: 'var(--pf-c1, #6429ed)',
        backgroundColor: 'var(--pf-c1, #6429ed)',
        color: '#ffffff',
        boxShadow: '0 10px 20px -5px color-mix(in srgb, var(--pf-c1, #6429ed) 25%, transparent)',
    },
    progressDone: {
        borderColor: 'color-mix(in srgb, #34d399 40%, transparent)',
        backgroundColor: 'color-mix(in srgb, #34d399 10%, transparent)',
        color: '#34d399',
    },
    progressIdle: {
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 70%, transparent)',
    },
    progressIcon: { height: '1rem', width: '1rem' },
    progressLabel: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.5rem',
        fontSize: '11px',
        fontWeight: 500,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 70%, transparent)',
    },
    progressLabelOn: {
        color: 'color-mix(in srgb, var(--pf-text, #fff) 80%, transparent)',
    },
    progressLine: {
        marginInline: '1.5rem',
        height: '1px',
        width: '4rem',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        '@media (min-width: 40rem)': { width: '6rem' },
    },
    progressLineOn: {
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 40%, transparent)',
    },

    /* ── Security sidebar ──────────────────────────────────────── */
    sidebar: {
        '@media (min-width: 64rem)': {
            position: 'sticky',
            top: '6rem',
            alignSelf: 'flex-start',
        },
    },
    sidebarCard: {
        borderRadius: '1rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1.5rem',
    },
    sidebarHead: {
        marginBottom: '1.25rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sidebarTitle: {
        fontFamily: FONT_HEADING,
        fontSize: '1.25rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    sidebarList: {
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },
    sidebarRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBlock: '0.75rem',
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },
    sidebarRowLast: { borderBottomWidth: 0 },
    sidebarKey: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    sidebarVal: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 600,
        color: 'color-mix(in srgb, var(--pf-text, #fff) 80%, transparent)',
    },
    sidebarValDim: {
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 50%, transparent)',
    },
    sidebarStatus: {
        fontFamily: FONT_JAKARTA,
        display: 'flex',
        alignItems: 'center',
        gap: '0.375rem',
        fontSize: '0.75rem',
        fontWeight: 600,
    },
    checklistBlock: {
        marginTop: '1.25rem',
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        paddingTop: '1.25rem',
    },
    checklistHead: {
        fontFamily: FONT_JAKARTA,
        marginBottom: '0.75rem',
        fontSize: '10px',
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
    },
    checklistItem: {
        fontFamily: FONT_JAKARTA,
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        fontSize: '0.75rem',
    },
    miniCard: {
        marginTop: '1.25rem',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        padding: '1rem',
    },
    miniCardDanger: {
        borderColor: 'color-mix(in srgb, #f87171 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #f87171 10%, transparent)',
    },
    miniCardBody: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
    },
    miniCardIcon: { flexShrink: 0, height: '1rem', width: '1rem' },
    miniCardTitle: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 600,
    },
    miniCardText: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.25rem',
        fontSize: '11px',
        lineHeight: '1.625',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },

    /* ── Step review summary ───────────────────────────────────── */
    summaryCard: {
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
    },
    summaryHead: {
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        paddingInline: '1.25rem',
        paddingBlock: '1rem',
    },
    avatar: {
        display: 'flex',
        height: '2.75rem',
        width: '2.75rem',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.75rem',
        backgroundColor: 'var(--pf-c1, #6429ed)',
        fontFamily: FONT_HEADING,
        fontSize: '1.125rem',
        fontWeight: 700,
        color: '#ffffff',
    },
    summaryId: { minWidth: 0 },
    summaryName: {
        fontFamily: FONT_JAKARTA,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
    },
    summaryEmail: {
        fontFamily: FONT_JAKARTA,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    summaryGrid: {
        display: 'grid',
        gap: '0.75rem',
        paddingInline: '1.25rem',
        paddingBlock: '1rem',
        '@media (min-width: 40rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    },
    summaryLabel: {
        fontFamily: FONT_JAKARTA,
        fontSize: '10px',
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
    },
    summaryValue: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.25rem',
        fontSize: '0.875rem',
        fontWeight: 700,
    },
    decisionCard: {
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, #34d399 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #34d399 10%, transparent)',
        paddingInline: '1.25rem',
        paddingBlock: '1rem',
    },
    decisionHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    decisionBody: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
    },
    decisionIcon: { height: '1.25rem', width: '1.25rem', color: '#34d399' },
    decisionTitle: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
    },
    decisionText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: '#34d399',
    },

    /* ── Status colors (Alpine :class toggles) ─────────────────── */
    textSuccess: { color: '#34d399' },
    textDestructive: { color: '#f87171' },
    textWarning: { color: '#fbbf24' },
    textMuted: { color: 'var(--pf-text-muted, rgba(255,255,255,0.6))' },
    minW0: { minWidth: 0 },
    spaceY2: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
    },
    textMutedDim: {
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 50%, transparent)',
    },

    /* ── Social logins ─────────────────────────────────────────── */
    socialWrap: { marginTop: '1.5rem' },
    socialDivider: { position: 'relative' },
    socialDividerLine: {
        position: 'absolute',
        inset: 0,
        display: 'flex',
        alignItems: 'center',
    },
    socialDividerRule: {
        width: '100%',
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },
    socialDividerLabel: {
        position: 'relative',
        display: 'flex',
        justifyContent: 'center',
        fontSize: '0.875rem',
    },
    socialDividerText: {
        fontFamily: FONT_JAKARTA,
        backgroundColor: 'var(--pf-bg, #030712)',
        paddingInline: '0.75rem',
        fontSize: '0.75rem',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 70%, transparent)',
    },
    socialGrid: {
        marginTop: '1.25rem',
        display: 'grid',
        gap: '0.75rem',
    },
    socialGrid2: {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    socialBtn: {
        fontFamily: FONT_JAKARTA,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        paddingInline: '1rem',
        paddingBlock: '0.625rem',
        fontSize: '0.875rem',
        fontWeight: 500,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'all',
        transitionDuration: '200ms',
        ':hover': {
            borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
        ':active': { transform: 'scale(0.98)' },
    },
    socialBtnIcon: { width: '1rem', height: '1rem' },

    /* ── OTP login ─────────────────────────────────────────────── */
    otpInput: {
        textAlign: 'center',
        fontFamily: FONT_JAKARTA,
        fontSize: '1.25rem',
        fontWeight: 700,
        letterSpacing: '0.4em',
    },

    /* ── Security footer ───────────────────────────────────────── */
    secFooter: {
        fontFamily: FONT_JAKARTA,
        marginTop: '1rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.75rem',
        fontSize: '0.75rem',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 60%, transparent)',
    },
    secFooterItem: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
    },
    secFooterIcon: { height: '0.75rem', width: '0.75rem' },

    /* ── Transitions / motion (Alpine x-transition) ────────────── */
    fadeEnter: {
        transitionProperty: 'opacity, transform',
        transitionDuration: '200ms',
        transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
    },
    fadeStart: {
        opacity: 0,
        transform: 'translateY(0.25rem)',
    },
    spinner: {
        animationName: spin,
        animationDuration: '1s',
        animationIterationCount: 'infinite',
        animationTimingFunction: 'linear',
    },

    /* ── Icons ─────────────────────────────────────────────────── */
    iconXs: { height: '0.75rem', width: '0.75rem' },
    iconSm: { height: '1rem', width: '1rem' },
    iconMd: { height: '1.25rem', width: '1.25rem' },
    iconCurrent: { fill: 'currentColor' },
    iconStroke: { fill: 'none' },
    opacity25: { opacity: 0.25 },
    opacity75: { opacity: 0.75 },

    /* ── Dashboard ─────────────────────────────────────────────── */
    wFull: { width: '100%' },
    wAuto: {
        '@media (min-width: 40rem)': { width: 'auto' },
    },
    textLeft: { textAlign: 'left' },
    textCenter: { textAlign: 'center' },
    mt1: { marginTop: '0.25rem' },
    mt2: { marginTop: '0.5rem' },
    mt4: { marginTop: '1rem' },
    mt6: { marginTop: '1.5rem' },
    mb2: { marginBottom: '0.5rem' },
    mb6: { marginBottom: '1.5rem' },
    block: { display: 'block' },
    flexRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    justifyEnd: { justifyContent: 'flex-end' },
    justifyBetween: { justifyContent: 'space-between' },
    justifyCenter: { justifyContent: 'center' },
    pt2: { paddingTop: '0.5rem' },
    itemsCenter: { alignItems: 'center' },
    itemsStart: { alignItems: 'flex-start' },
    gap1: { gap: '0.25rem' },
    gap2: { gap: '0.5rem' },
    gap3: { gap: '0.75rem' },
    gap4: { gap: '1rem' },
    gap5: { gap: '1.25rem' },
    flexCol: { display: 'flex', flexDirection: 'column' },
    flexColRev: { display: 'flex', flexDirection: 'column-reverse' },
    grid2: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
        gap: '0.75rem',
    },
    formGrid2: {
        display: 'grid',
        gap: '0.75rem',
        '@media (min-width: 40rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    },
    formColFull: { gridColumn: '1 / -1' },
    phoneRow: { display: 'flex', gap: '0.75rem', alignItems: 'flex-start' },
    phoneCode: { width: '45%', minWidth: '7.5rem', maxWidth: '13rem', flexShrink: 0 },
    phoneGrow: { flex: '1 1 0%', minWidth: 0 },
    phoneCodeMenu: {
        position: 'absolute',
        top: 'calc(100% + 0.375rem)',
        left: 0,
        right: 0,
        zIndex: 30,
        maxHeight: '14rem',
        overflowY: 'auto',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 12%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.4)',
        padding: '0.25rem',
        margin: 0,
        listStyle: 'none',
        textAlign: 'left',
    },
    phoneCodeOption: {
        display: 'block',
        width: '100%',
        paddingInline: '0.75rem',
        paddingBlock: '0.5rem',
        borderRadius: '0.5rem',
        cursor: 'pointer',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    phoneCodeEmpty: {
        paddingInline: '0.75rem',
        paddingBlock: '0.5rem',
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    phoneCodeChevron: {
        position: 'absolute',
        top: '50%',
        right: '0.875rem',
        transform: 'translateY(-50%)',
        pointerEvents: 'none',
    },
    px5: { paddingInline: '1.25rem' },
    py4: { paddingBlock: '1rem' },
    borderBottom: {
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },

    dashTitle: {
        fontSize: '1.5rem',
        fontWeight: 600,
        letterSpacing: '-0.025em',
        color: 'var(--pf-text, #fff)',
    },
    dashText: {
        marginTop: '0.5rem',
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    dashGrid: {
        marginTop: '2rem',
        display: 'grid',
        gap: '1rem',
        '@media (min-width: 40rem)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    },
    dashCard: {
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1.5rem',
        boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
    },
    dashCardTitle: {
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
    },
    dashCardText: {
        marginTop: '0.25rem',
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    codeTag: {
        borderRadius: '0.25rem',
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 4%, transparent)',
        paddingInline: '0.25rem',
        paddingBlock: '0.125rem',
        fontSize: '0.75rem',
    },

    /* ── Home page ─────────────────────────────────────────────── */
    homeBody: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--pf-bg, #030712)',
        color: 'var(--pf-text, #ffffff)',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
    },
    homeHeader: {
        width: '100%',
        maxWidth: '64rem',
        marginInline: 'auto',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingInline: '1.5rem',
        paddingBlock: '1.25rem',
        '@media (min-width: 40rem)': { paddingInline: '2rem' },
    },
    homeBrand: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.625rem',
    },
    homeBrandMark: {
        display: 'flex',
        height: '2rem',
        width: '2rem',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.5rem',
        backgroundColor: 'var(--pf-c1, #6429ed)',
        color: '#ffffff',
        fontSize: '0.75rem',
        fontWeight: 700,
    },
    homeBrandText: {
        fontFamily: FONT_HEADING,
        fontSize: '1.5rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    homeNav: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    homeNavBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.5rem',
        paddingInline: '1rem',
        paddingBlock: '0.5rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 500,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, border-color, background-color',
        transitionDuration: '200ms',
        ':hover': { color: 'var(--pf-text, #fff)' },
    },
    homeNavBtnPrimary: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 40%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 15%, transparent)',
        color: 'var(--pf-text, #fff)',
        ':hover': {
            borderColor: 'var(--pf-c1, #6429ed)',
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 25%, transparent)',
        },
    },
    homeHero: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        paddingInline: '1.5rem',
        paddingBlock: '4rem',
        '@media (min-width: 40rem)': { paddingInline: '2rem' },
    },
    homeHeroBadge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
        borderRadius: '9999px',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-c2, #a855f7) 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-c2, #a855f7) 10%, transparent)',
        paddingInline: '0.875rem',
        paddingBlock: '0.375rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        fontWeight: 600,
        letterSpacing: '0.05em',
        textTransform: 'uppercase',
        color: 'var(--pf-c2, #a855f7)',
    },
    homeHeroTitle: {
        fontFamily: FONT_HEADING,
        marginTop: '1.5rem',
        maxWidth: '48rem',
        fontSize: '3.5rem',
        fontWeight: 700,
        letterSpacing: '-0.02em',
        lineHeight: 0.95,
        color: 'var(--pf-text, #fff)',
        '@media (min-width: 40rem)': { fontSize: '5rem' },
        '@media (min-width: 64rem)': { fontSize: '6rem' },
    },
    homeHeroTitleAccent: {
        backgroundImage: 'linear-gradient(to right, var(--pf-c1, #6429ed), var(--pf-accent, #00e5fd))',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        color: 'transparent',
    },
    homeHeroSub: {
        fontFamily: FONT_JAKARTA,
        marginTop: '1.25rem',
        maxWidth: '36rem',
        fontSize: '1.0625rem',
        lineHeight: 1.7,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    homeCtaRow: {
        marginTop: '2.5rem',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '0.75rem',
        '@media (min-width: 40rem)': { flexDirection: 'row' },
    },
    homeCtaPrimary: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        borderRadius: '0.75rem',
        backgroundColor: 'var(--pf-c1, #6429ed)',
        paddingInline: '1.75rem',
        paddingBlock: '0.75rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.9375rem',
        fontWeight: 700,
        color: '#ffffff',
        boxShadow: '0 10px 20px -5px color-mix(in srgb, var(--pf-c1, #6429ed) 30%, transparent)',
        transitionProperty: 'background-color, transform, box-shadow',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 85%, transparent)',
            boxShadow: '0 10px 25px -5px color-mix(in srgb, var(--pf-c1, #6429ed) 40%, transparent)',
        },
        ':active': { transform: 'scale(0.98)' },
    },
    homeCtaGhost: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 16%, transparent)',
        paddingInline: '1.75rem',
        paddingBlock: '0.75rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.9375rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
        transitionProperty: 'background-color, transform',
        transitionDuration: '200ms',
        ':hover': { backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)' },
        ':active': { transform: 'scale(0.98)' },
    },
    homeFeatures: {
        display: 'grid',
        gap: '1.25rem',
        maxWidth: '64rem',
        marginInline: 'auto',
        paddingInline: '1.5rem',
        paddingBottom: '5rem',
        '@media (min-width: 40rem)': {
            paddingInline: '2rem',
            gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        },
    },
    homeSection: {
        maxWidth: '64rem',
        marginInline: 'auto',
        paddingInline: '1.5rem',
        paddingBlock: '3rem',
        '@media (min-width: 40rem)': { paddingInline: '2rem' },
        '@media (min-width: 64rem)': { paddingBlock: '4rem' },
    },
    homeSectionAlt: {
        backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 2%, transparent)',
        maxWidth: 'none',
    },
    homeSectionInner: {
        maxWidth: '64rem',
        marginInline: 'auto',
    },
    homeSectionHead: {
        maxWidth: '42rem',
        marginBottom: '2.5rem',
    },
    homeSectionHeadCenter: {
        marginInline: 'auto',
        textAlign: 'center',
    },
    homeEyebrow: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.6875rem',
        fontWeight: 700,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        color: 'var(--pf-accent, #00e5fd)',
    },
    homeSectionTitle: {
        fontFamily: FONT_HEADING,
        marginTop: '0.75rem',
        fontSize: '2.25rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        lineHeight: 1.1,
        color: 'var(--pf-text, #fff)',
        '@media (min-width: 40rem)': { fontSize: '2.75rem' },
    },
    homeSectionSub: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.75rem',
        fontSize: '0.9375rem',
        lineHeight: 1.7,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    homeSectionGrid: {
        display: 'grid',
        gap: '1.25rem',
        '@media (min-width: 40rem)': {
            gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        },
    },
    homeFeatureCard: {
        height: '100%',
        borderRadius: '1rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1.5rem',
        transitionProperty: 'border-color, transform',
        transitionDuration: '200ms',
        ':hover': {
            borderColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 40%, transparent)',
            transform: 'translateY(-2px)',
        },
    },
    homeFeatureIcon: {
        display: 'flex',
        height: '2.5rem',
        width: '2.5rem',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.75rem',
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 15%, transparent)',
        color: 'var(--pf-c1, #6429ed)',
    },
    homeFeatureTitle: {
        fontFamily: FONT_HEADING,
        marginTop: '1rem',
        fontSize: '1.375rem',
        fontWeight: 600,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    homeFeatureText: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.5rem',
        fontSize: '0.875rem',
        lineHeight: 1.625,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    homeCtaBanner: {
        position: 'relative',
        overflow: 'hidden',
        borderRadius: '1.5rem',
        paddingInline: '2rem',
        paddingBlock: '3rem',
        textAlign: 'center',
        backgroundImage: 'linear-gradient(135deg, color-mix(in srgb, var(--pf-c1, #6429ed) 90%, transparent), color-mix(in srgb, var(--pf-c2, #a855f7) 90%, transparent))',
        '@media (min-width: 40rem)': { paddingBlock: '4rem' },
    },
    homeCtaBannerTitle: {
        fontFamily: FONT_HEADING,
        fontSize: '2.5rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        lineHeight: 1.1,
        color: '#ffffff',
        '@media (min-width: 40rem)': { fontSize: '3.25rem' },
    },
    homeCtaBannerText: {
        fontFamily: FONT_JAKARTA,
        marginInline: 'auto',
        marginTop: '0.75rem',
        maxWidth: '34rem',
        fontSize: '0.9375rem',
        lineHeight: 1.7,
        color: 'color-mix(in srgb, #ffffff 85%, transparent)',
    },
    homeCtaBannerBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        marginTop: '2rem',
        borderRadius: '0.75rem',
        backgroundColor: '#ffffff',
        paddingInline: '1.75rem',
        paddingBlock: '0.75rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.9375rem',
        fontWeight: 700,
        color: 'var(--pf-c1, #6429ed)',
        boxShadow: '0 10px 20px -5px rgba(0, 0, 0, 0.25)',
        transitionProperty: 'transform, box-shadow',
        transitionDuration: '200ms',
        ':hover': {
            transform: 'translateY(-2px)',
            boxShadow: '0 15px 25px -5px rgba(0, 0, 0, 0.3)',
        },
        ':active': { transform: 'scale(0.98)' },
    },
    homeFooter: {
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
        paddingBlock: '2rem',
        textAlign: 'center',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 60%, transparent)',
    },

    /* ── Admin layout ─────────────────────────────────────────── */
    adminShell: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
    },
    adminLayout: {
        position: 'relative',
        flex: 1,
        display: 'flex',
        minHeight: 0,
    },
    adminSidebar: {
        display: 'none',
        '@media (min-width: 64rem)': {
            display: 'block',
            position: 'sticky',
            top: '4rem',
            height: 'calc(100vh - 4rem)',
            width: '15rem',
            flexShrink: 0,
            overflowY: 'auto',
            borderRightWidth: 1,
            borderRightStyle: 'solid',
            borderRightColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
            paddingBlock: '1.5rem',
            paddingInline: '1rem',
        },
    },
    adminNav: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.25rem',
    },
    adminNavLabel: {
        fontFamily: FONT_MONO,
        marginBottom: '0.25rem',
        paddingInline: '0.75rem',
        fontSize: '10px',
        fontWeight: 600,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 60%, transparent)',
    },
    adminNavLink: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.625rem',
        borderRadius: '0.5rem',
        paddingInline: '0.75rem',
        paddingBlock: '0.5rem',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    adminNavLinkActive: {
        backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 12%, transparent)',
        color: 'var(--pf-c1, #6429ed)',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 18%, transparent)',
            color: 'var(--pf-c1, #6429ed)',
        },
    },
    adminNavIcon: { flexShrink: 0, height: '1rem', width: '1rem' },
    adminMain: { flex: 1, minWidth: 0 },
    adminMenuBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2.25rem',
        width: '2.25rem',
        borderRadius: '0.5rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
        '@media (min-width: 64rem)': { display: 'none' },
    },
    adminDrawer: {
        position: 'fixed',
        insetBlock: 0,
        left: 0,
        zIndex: 50,
        display: 'flex',
        width: '17rem',
        flexDirection: 'column',
        overflowY: 'auto',
        borderRightWidth: 1,
        borderRightStyle: 'solid',
        borderRightColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1rem',
        transform: 'translateX(-100%)',
        transitionProperty: 'transform',
        transitionDuration: '300ms',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        '@media (min-width: 64rem)': { display: 'none' },
    },
    adminDrawerOpen: {
        transform: 'translateX(0)',
    },
    adminDrawerHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '1.5rem',
    },
    adminOverlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 40,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(2px)',
        '@media (min-width: 64rem)': { display: 'none' },
    },

    /* ── App drawer & overlay ──────────────────────────────────── */
    appDrawer: {
        position: 'fixed',
        insetBlock: 0,
        left: 0,
        zIndex: 50,
        display: 'flex',
        width: '17rem',
        flexDirection: 'column',
        overflowY: 'auto',
        borderRightWidth: 1,
        borderRightStyle: 'solid',
        borderRightColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1rem',
        transform: 'translateX(-100%)',
        transitionProperty: 'transform',
        transitionDuration: '300ms',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        '@media (min-width: 64rem)': { display: 'none' },
    },
    appDrawerOpen: {
        transform: 'translateX(0)',
    },
    appDrawerHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '1.5rem',
    },
    appOverlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 40,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(2px)',
        '@media (min-width: 64rem)': { display: 'none' },
    },
    appFooter: {
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
        paddingBlock: '1.5rem',
        paddingInline: '1rem',
        textAlign: 'center',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.75rem',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 60%, transparent)',
    },

    /* ── Admin header & theme switcher ────────────────────────── */
    adminHeaderActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
    },
    themeWrap: {
        position: 'relative',
    },
    themeIndicator: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.375rem',
        borderWidth: 0,
        backgroundColor: 'transparent',
        borderRadius: '0.4rem',
        paddingInline: '0.5rem',
        paddingBlock: '0.25rem',
        fontFamily: FONT_MONO,
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        cursor: 'pointer',
        transitionProperty: 'color, background-color',
        transitionDuration: '160ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-accent, #00e5fd) 55%, transparent)',
        },
    },
    themeIndicSep: {
        color: 'color-mix(in srgb, var(--pf-accent, #00e5fd) 55%, transparent)',
    },
    themeIndicName: {
        fontWeight: 600,
        whiteSpace: 'nowrap',
    },
    caretIcon: {
        width: '0.625rem',
        height: '0.625rem',
        flexShrink: 0,
    },
    tnum: {
        fontVariantNumeric: 'tabular-nums',
    },
    themeShuffle: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.3rem',
        borderWidth: 0,
        backgroundColor: 'transparent',
        borderRadius: '0.4rem',
        paddingInline: '0.4rem',
        paddingBlock: '0.25rem',
        fontFamily: FONT_MONO,
        fontSize: '0.625rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        cursor: 'pointer',
        transitionProperty: 'color, transform',
        transitionDuration: '160ms',
        ':hover': {
            color: 'var(--pf-accent, #00e5fd)',
        },
        ':active': {
            transform: 'translateY(1px)',
        },
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-accent, #00e5fd) 55%, transparent)',
        },
    },
    themeShuffleKey: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 18%, transparent)',
        borderRadius: '0.25rem',
        paddingInline: '0.25rem',
        lineHeight: 1.2,
    },
    themeMenu: {
        position: 'absolute',
        top: 'calc(100% + 0.5rem)',
        right: 0,
        zIndex: 100,
        width: '18rem',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 12%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-surface, #111827) 92%, transparent)',
        backdropFilter: 'blur(24px) saturate(1.4)',
        boxShadow: '0 2px 0 -1px color-mix(in srgb, var(--pf-text, #fff) 6%, transparent), 0 20px 50px -20px rgba(0, 0, 0, 0.6)',
        padding: '0.375rem',
    },
    themeDotGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(7, 1fr)',
        gap: '0.5rem',
        padding: '0.625rem',
        borderRadius: '0.5rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-f2, #161b22) 55%, transparent)',
        boxShadow: 'inset 0 1px 0 color-mix(in srgb, var(--pf-text, #fff) 5%, transparent)',
    },
    themeDot: {
        position: 'relative',
        display: 'grid',
        placeItems: 'center',
        width: '1.5rem',
        height: '1.5rem',
        borderWidth: 0,
        borderRadius: '0.375rem',
        cursor: 'pointer',
        backgroundColor: 'var(--dot, #f7f5ec)',
        color: 'var(--num, #442324)',
        boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--dot-edge, #ff3a5d) 25%, transparent)',
        transitionProperty: 'transform, box-shadow',
        transitionDuration: '160ms',
        transitionTimingFunction: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        ':hover': {
            transform: 'scale(1.16)',
            boxShadow: '0 0 0 2px var(--dot-edge, #ff3a5d)',
        },
        ':active': {
            transform: 'scale(1.02) translateY(1px)',
        },
        ':focus-visible': {
            outline: '2px solid color-mix(in srgb, var(--dot-edge, #ff3a5d) 75%, transparent)',
            outlineOffset: '2px',
        },
        '@media (prefers-reduced-motion: reduce)': {
            transitionDuration: '0ms',
            transitionTimingFunction: 'linear',
        },
    },
    themeDotActive: {
        transform: 'scale(1.16)',
        boxShadow: '0 0 0 2px var(--dot-edge, #ff3a5d), 0 0 16px -2px var(--dot-edge, #ff3a5d)',
    },
    themeDotNum: {
        fontFamily: FONT_MONO,
        fontSize: '0.5625rem',
        fontWeight: 600,
        lineHeight: 1,
        fontVariantNumeric: 'tabular-nums',
        pointerEvents: 'none',
    },
    bannerMark: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
        textDecoration: 'none',
        color: 'var(--pf-text, #fff)',
    },
    brandSlash: {
        fontFamily: FONT_MONO,
        fontWeight: 600,
        fontSize: '0.9375rem',
        lineHeight: 1,
        color: 'var(--pf-accent, #00e5fd)',
    },
    brandName: {
        fontFamily: FONT_HEADING,
        fontSize: '1.25rem',
        fontWeight: 600,
        letterSpacing: '0.02em',
        lineHeight: 1,
        color: 'color-mix(in srgb, var(--pf-text, #fff) 92%, transparent)',
    },
    bannerVer: {
        fontFamily: FONT_MONO,
        fontSize: '0.5625rem',
        fontWeight: 500,
        letterSpacing: '0.08em',
        fontVariantNumeric: 'tabular-nums',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 14%, transparent)',
        borderRadius: '9999px',
        paddingInline: '0.35rem',
        paddingBlock: '0.0625rem',
    },
    bannerSpacer: {
        flex: 1,
    },

    /* ── User management (admin) ─────────────────────────────── */
    tableCard: {
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
    },
    tableWrap: {
        overflowX: 'auto',
    },
    table: {
        width: '100%',
        minWidth: '42rem',
        borderCollapse: 'collapse',
    },
    tableHead: {
        fontFamily: FONT_MONO,
        paddingInline: '1.25rem',
        paddingBlock: '0.75rem',
        fontSize: '11px',
        fontWeight: 600,
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 80%, transparent)',
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },
    tableHeadRight: {
        textAlign: 'right',
    },
    tbodyRow: {
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
        transitionProperty: 'background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 3%, transparent)',
        },
    },
    tbodyRowLast: {
        borderBottomWidth: 0,
    },
    tableCell: {
        fontFamily: FONT_JAKARTA,
        paddingInline: '1.25rem',
        paddingBlock: '0.875rem',
        fontSize: '0.875rem',
        color: 'var(--pf-text, #fff)',
        verticalAlign: 'middle',
    },
    tableCellRight: {
        textAlign: 'right',
        whiteSpace: 'nowrap',
    },
    cellUser: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
    },
    avatarSm: {
        display: 'flex',
        height: '2rem',
        width: '2rem',
        flexShrink: 0,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '0.5rem',
        backgroundColor: 'var(--pf-c1, #6429ed)',
        fontFamily: FONT_HEADING,
        fontSize: '0.875rem',
        fontWeight: 700,
        color: '#ffffff',
    },
    cellName: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
    },
    cellUsername: {
        fontFamily: FONT_MONO,
        marginTop: '0.125rem',
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    cellEmail: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    rowActions: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: '0.375rem',
    },
    actionBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2rem',
        width: '2rem',
        borderRadius: '0.5rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    actionBtnDanger: {
        ':hover': {
            backgroundColor: 'color-mix(in srgb, #f87171 12%, transparent)',
            color: '#f87171',
        },
    },
    roleCell: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '0.375rem',
    },
    toolbar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '1rem',
        marginBottom: '1.5rem',
    },
    searchBox: {
        position: 'relative',
        width: 'min(100%, 22rem)',
    },
    searchIcon: {
        position: 'absolute',
        top: '50%',
        left: '0.875rem',
        transform: 'translateY(-50%)',
        height: '1rem',
        width: '1rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        pointerEvents: 'none',
    },
    searchPad: {
        paddingLeft: '2.5rem',
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        paddingBlock: '3rem',
        textAlign: 'center',
    },
    emptyIcon: {
        height: '2rem',
        width: '2rem',
        color: 'color-mix(in srgb, var(--pf-text-muted, rgba(255,255,255,0.6)) 50%, transparent)',
    },
    emptyTitle: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        fontWeight: 600,
        color: 'var(--pf-text, #fff)',
    },
    emptyText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    pagFooter: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '1rem',
        marginTop: '1rem',
    },
    pagInfo: {
        fontFamily: FONT_MONO,
        fontSize: '0.75rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    pagNav: {
        display: 'inline-flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        gap: '0.375rem',
    },
    pageNum: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2.25rem',
        minWidth: '2.25rem',
        paddingInline: '0.625rem',
        borderRadius: '0.5rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 12%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color, border-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 6%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
    },
    pageNumActive: {
        backgroundColor: 'var(--pf-c1, #6429ed)',
        borderColor: 'var(--pf-c1, #6429ed)',
        color: '#ffffff',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-c1, #6429ed) 90%, transparent)',
            color: '#ffffff',
        },
    },
    pageNumDisabled: {
        opacity: 0.4,
        pointerEvents: 'none',
    },
    pageNumDots: {
        display: 'inline-flex',
        alignItems: 'center',
        height: '2.25rem',
        paddingInline: '0.25rem',
        fontFamily: FONT_MONO,
        fontSize: '0.875rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    formHeading: {
        fontFamily: FONT_HEADING,
        fontSize: '1.375rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    roleGrid: {
        display: 'grid',
        gap: '0.5rem',
        gridTemplateColumns: 'repeat(auto-fill, minmax(8rem, 1fr))',
    },
    formFooter: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: '0.75rem',
        paddingTop: '1.5rem',
        borderTopWidth: 1,
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
    },

    /* ── Confirm and notice modals ────────────────────────────── */
    modalBackdrop: {
        position: 'fixed',
        inset: 0,
        zIndex: 60,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '1rem',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(2px)',
    },
    modalCard: {
        position: 'relative',
        width: '100%',
        maxWidth: '26rem',
        maxHeight: 'calc(100vh - 2rem)',
        overflowY: 'auto',
        borderRadius: '0.75rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 10%, transparent)',
        backgroundColor: 'var(--pf-surface, #111827)',
        padding: '1.25rem',
        boxShadow: '0 20px 60px -20px rgba(0, 0, 0, 0.6)',
        '@media (min-width: 40rem)': { padding: '1.5rem' },
    },
    modalHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
        paddingRight: '2rem',
    },
    modalIconWrap: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2.5rem',
        width: '2.5rem',
        flexShrink: 0,
        borderRadius: '0.75rem',
        backgroundColor: 'color-mix(in srgb, #f87171 14%, transparent)',
        color: '#f87171',
    },
    modalIconWrapWarning: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2.5rem',
        width: '2.5rem',
        flexShrink: 0,
        borderRadius: '0.75rem',
        backgroundColor: 'color-mix(in srgb, #fbbf24 14%, transparent)',
        color: '#fbbf24',
    },
    modalClose: {
        position: 'absolute',
        top: '0.5rem',
        right: '0.5rem',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2rem',
        width: '2rem',
        borderRadius: '0.5rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 60%, transparent)',
        },
    },
    modalTitle: {
        fontFamily: FONT_HEADING,
        fontSize: '1.25rem',
        fontWeight: 700,
        letterSpacing: '0.025em',
        color: 'var(--pf-text, #fff)',
    },
    modalText: {
        fontFamily: FONT_JAKARTA,
        fontSize: '0.875rem',
        lineHeight: 1.5,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    modalPop: {
        transitionProperty: 'opacity, transform',
        transitionDuration: '200ms',
        transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
    },
    modalScale: {
        opacity: 0,
        transform: 'scale(0.96)',
    },

    /* ── Sign-in notice modal ──────────────────────────────────── */
    noticeBackdrop: {
        position: 'fixed',
        inset: 0,
        zIndex: 60,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '1rem',
        backgroundColor: 'rgba(0, 0, 0, 0.65)',
        backdropFilter: 'blur(12px)',
    },
    noticeCard: {
        position: 'relative',
        overflow: 'hidden',
        width: '100%',
        maxWidth: '27.5rem',
        maxHeight: 'calc(100vh - 2rem)',
        overflowY: 'auto',
        borderRadius: '1.25rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--pf-text, #fff) 12%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--pf-surface, #111827) 92%, transparent)',
        backdropFilter: 'blur(28px) saturate(1.4)',
        padding: '1.5rem',
        boxShadow: '0 2px 0 -1px color-mix(in srgb, var(--pf-text, #fff) 6%, transparent), 0 20px 50px -20px rgba(0, 0, 0, 0.65)',
        '@media (min-width: 40rem)': { padding: '1.75rem' },
    },
    noticeBar: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '3px',
        backgroundImage: 'linear-gradient(135deg, var(--pf-c1, #6429ed), var(--pf-c2, #a855f7), var(--pf-accent, #00e5fd))',
    },
    noticeGlow: {
        position: 'absolute',
        top: '-4.5rem',
        right: '-3.5rem',
        width: '12rem',
        height: '12rem',
        borderRadius: '9999px',
        pointerEvents: 'none',
        backgroundImage: 'radial-gradient(circle at center, color-mix(in srgb, #f87171 35%, transparent), transparent 70%)',
    },
    noticeGlowWarning: {
        position: 'absolute',
        top: '-4.5rem',
        right: '-3.5rem',
        width: '12rem',
        height: '12rem',
        borderRadius: '9999px',
        pointerEvents: 'none',
        backgroundImage: 'radial-gradient(circle at center, color-mix(in srgb, #fbbf24 32%, transparent), transparent 70%)',
    },
    noticeHeader: {
        position: 'relative',
        zIndex: 1,
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.875rem',
        paddingRight: '2rem',
    },
    noticeIconWrap: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '3rem',
        width: '3rem',
        flexShrink: 0,
        borderRadius: '0.875rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, #f87171 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #f87171 14%, transparent)',
        color: '#f87171',
        boxShadow: '0 8px 24px -10px color-mix(in srgb, #f87171 55%, transparent)',
    },
    noticeIconWrapWarning: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '3rem',
        width: '3rem',
        flexShrink: 0,
        borderRadius: '0.875rem',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, #fbbf24 25%, transparent)',
        backgroundColor: 'color-mix(in srgb, #fbbf24 14%, transparent)',
        color: '#fbbf24',
        boxShadow: '0 8px 24px -10px color-mix(in srgb, #fbbf24 55%, transparent)',
    },
    noticeIcon: { height: '1.5rem', width: '1.5rem' },
    noticeKicker: {
        fontFamily: FONT_MONO,
        fontSize: '0.6875rem',
        fontWeight: 600,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    noticeTitle: {
        display: 'block',
        fontFamily: FONT_HEADING,
        marginTop: '0.25rem',
        fontSize: '1.75rem',
        fontWeight: 700,
        letterSpacing: '0.01em',
        lineHeight: 1.1,
        color: 'var(--pf-text, #fff)',
    },
    noticeText: {
        fontFamily: FONT_JAKARTA,
        marginTop: '0.5rem',
        fontSize: '0.875rem',
        lineHeight: 1.6,
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
    },
    noticeClose: {
        position: 'absolute',
        top: '0.75rem',
        right: '0.75rem',
        zIndex: 1,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '2.25rem',
        width: '2.25rem',
        borderRadius: '0.625rem',
        color: 'var(--pf-text-muted, rgba(255,255,255,0.6))',
        transitionProperty: 'color, background-color',
        transitionDuration: '200ms',
        ':hover': {
            backgroundColor: 'color-mix(in srgb, var(--pf-text, #fff) 8%, transparent)',
            color: 'var(--pf-text, #fff)',
        },
        ':focus-visible': {
            outline: 'none',
            boxShadow: '0 0 0 2px color-mix(in srgb, var(--pf-c1, #6429ed) 60%, transparent)',
        },
    },
    noticePop: {
        transitionProperty: 'opacity, transform',
        transitionDuration: '240ms',
        transitionTimingFunction: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        '@media (prefers-reduced-motion: reduce)': {
            transitionDuration: '0ms',
            transitionTimingFunction: 'linear',
        },
    },
    noticeScale: {
        opacity: 0,
        transform: 'scale(0.92) translateY(8px)',
    },
});